services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    hostname: zookeeper
    restart: unless-stopped
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  kafka1:
    image: confluentinc/cp-kafka:7.5.0
    hostname: kafka1
    restart: unless-stopped
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka1:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
      KAFKA_ALLOW_AUTO_TOPIC_CREATION: "true"
    deploy:
      resources:
        limits:
          memory: 1.5G
        reservations:
          memory: 1G

  # kafka2:
  #   image: confluentinc/cp-kafka:7.5.0
  #   hostname: kafka2
  #   restart: unless-stopped
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9093:9093"
  #   environment:
  #     KAFKA_BROKER_ID: 2
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9093
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka2:9093
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     KAFKA_ALLOW_AUTO_TOPIC_CREATION: "true"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1.5G
  #       reservations:
  #         memory: 1G

  # kafka3:
  #   image: confluentinc/cp-kafka:7.5.0
  #   hostname: kafka3
  #   restart: unless-stopped
  #   depends_on:
  #     - zookeeper
  #   ports:
  #     - "9094:9094"
  #   environment:
  #     KAFKA_BROKER_ID: 3
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9094
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka3:9094
  #     KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT
  #     KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #     KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
  #     KAFKA_ALLOW_AUTO_TOPIC_CREATION: "true"
  #   deploy:
  #     resources:
  #       limits:
  #         memory: 1.5G
  #       reservations:
  #         memory: 1G

  schema-registry:
    image: confluentinc/cp-schema-registry:7.5.0
    hostname: schema-registry
    restart: unless-stopped
    depends_on:
      - kafka1 # Para depender de vários brokers, liste cada serviço Kafka em depends_on, por exemplo: kafka1, kafka2, kafka3
    ports:
      - "8081:8081"
    environment:
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: |
        PLAINTEXT://kafka1:9092,
        PLAINTEXT://kafka2:9093,
        PLAINTEXT://kafka3:9094
      SCHEMA_REGISTRY_KAFKASTORE_TOPIC: _schemas
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    hostname: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka1 # Para depender de vários brokers, liste cada serviço Kafka em depends_on, por exemplo: kafka1, kafka2, kafka3
      - schema-registry
    ports:
      - "8080:8080"
    environment:
      KAFKA_CLUSTERS_0_NAME: local-kafka
      KAFKA_CLUSTERS_0_BOOTSTRAP_SERVERS: kafka1:9092,kafka2:9093,kafka3:9094
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_ZOOKEEPER: zookeeper:2181
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 256M
